version: '2'

services:
  dev:
    build:
      context: .
    volumes:
      - ./database:/usr/src/wordpress/wp-content/database
      - ./uploads:/usr/src/wordpress/wp-content/uploads
      - ./plugins:/usr/src/wordpress/wp-content/plugins
      - ./themes:/usr/src/wordpress/wp-content/themes
      - ./wp-config.php:/usr/src/wordpress/wp-config.php
    restart: always
    entrypoint: sh -c "cd /usr/src/wordpress && php -S 0.0.0.0:${RHPORT}"
    ports:
      - "${RHPORT}:${RHPORT}"
    user: ${CURRENT_UID}
    network_mode: "host"
